AWSTemplateFormatVersion: '2010-09-09'
Description: 'NLB'
Parameters:
  Env:
    Type: String
  VPC:
    Type: AWS::EC2::VPC::Id
  NLB:
    Type: String


Resources:
  DNSTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 53
      Protocol: TCP_UDP
      VpcId: !Ref VPC
      HealthCheckEnabled: true
      HealthCheckPort: 53
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      HealthCheckProtocol: TCP

  DNSNLBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref DNSTargetGroup
      LoadBalancerArn: !Ref NLB
      Port: 53
      Protocol: TCP_UDP

Outputs:
  DNSTargetGroup:
    Value: !Ref DNSTargetGroup

