AWSTemplateFormatVersion: '2010-09-09'
Description: 'cidr ingress'
Parameters:
  DestinationSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  SourceCIDR:
    Type: String
  Port:
    Type: Number
  Protocol:
    Type: String
    Default: tcp
Resources:
  ServiceIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref DestinationSecurityGroup
      IpProtocol: !Ref Protocol
      FromPort: !Ref Port
      ToPort: !Ref Port
      CidrIp: !Ref SourceCIDR
