AWSTemplateFormatVersion: '2010-09-09'
Description: 'sg to sg ingress'
Parameters:
  SourceSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  DestinationSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  Port:
    Type: Number
Resources:
  ServiceIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref DestinationSecurityGroup
      IpProtocol: tcp
      FromPort: !Ref Port
      ToPort: !Ref Port
      SourceSecurityGroupId: !Ref SourceSecurityGroup
