AWSTemplateFormatVersion: '2010-09-09'
Description: 'Service ASG'
Parameters:
  Env:
    Type: String
  VPC:
    Type: AWS::EC2::VPC::Id
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
  AMI:
    Type: 'AWS::EC2::Image::Id'
  InstanceType:
    Type: String
    Default: t3a.nano
  InstanceQty:
    Type: Number
    Default: 3
  ServiceName:
    Type: String
  ServiceConfig:
    Type: String

Resources:
  ServiceLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref AMI
      SecurityGroups:
        - !Ref ServiceSecurityGroup
      InstanceType: !Ref InstanceType
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: 2
            VolumeType: gp3
            DeleteOnTermination: "true"

  ASService:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: !Ref SubnetIds
      LaunchConfigurationName: !Ref ServiceLaunchConfig
      TerminationPolicies:
        - OldestInstance
      DesiredCapacity: !Ref InstanceQty
      MinSize: '0'
      MaxSize: !Ref InstanceQty
      Tags:
        - Key: Name
          Value: !Sub '${Env}-${ServiceName}-Service'
          PropagateAtLaunch: 'true'
        - Key: consulcloud
          Value: service
          PropagateAtLaunch: 'true'  
        - Key: consulserviceconfig
          Value: !Ref ServiceConfig
          PropagateAtLaunch: 'true'  
  ServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub '${ServiceName} ingress'
      VpcId: !Ref VPC
      SecurityGroupEgress:
      - IpProtocol: -1
        CidrIp: 0.0.0.0/0



Outputs:
  SecurityGroup:
    Value: !Ref ServiceSecurityGroup
