AWSTemplateFormatVersion: '2010-09-09'
Description: 'Service ASG'
Parameters:
  Env:
    Type: String
  ServiceName:
    Type: String
  ConsulConfig:
    Type: String
  ASGToConsulRole:
    Type: String

Resources:
  ServiceConfig:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value:
        Fn::Base64:
          !Sub |
            ${ConsulConfig}    
      Description: !Sub '${Env} ${ServiceName} config'

  ServiceConfigAccess:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Sub 'ConsulParamAccess-${ServiceName}'
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'ssm:GetParameters'
              - 'ssm:GetParameter'
              - 'ssm:GetParametersByPath'
            Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ServiceConfig}'
      Roles:
        - !Ref ASGToConsulRole
Outputs:
  ServiceConfig:
    Value: !Ref ServiceConfig
