AWSTemplateFormatVersion: '2010-09-09'
Description: 'NLB'
Parameters:
  Env:
    Type: String
  VPC:
    Type: AWS::EC2::VPC::Id
  NLB:
    Type: String


Resources:
  LoggerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 514
      Protocol: TCP_UDP
      VpcId: !Ref VPC
      HealthCheckEnabled: true
      HealthCheckPort: 2020
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      HealthCheckProtocol: HTTP

  LoggerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref LoggerTargetGroup
      LoadBalancerArn: !Ref NLB
      Port: 514
      Protocol: TCP_UDP

Outputs:
  TargetGroup:
    Value: !Ref LoggerTargetGroup

