pipeline:
  adserviceimageclone:
    image: bitnami/git:latest
    commands:
      - git clone https://github.com/GoogleCloudPlatform/microservices-demo.git
  adserviceimagebuild:
    image: openjdk:8-slim
    commands:
      - cd microservices-demo/src/adservice
      - chmod +x gradlew
      - ./gradlew downloadRepos
      - ./gradlew installDist
  adserviceimagepush:
    image: jasonrichardsmith/ops:0.1.28.3
    secrets: [aws_access_key_id, aws_secret_access_key, bucket]
    commands:
      - echo $BUCKET > /tmp/bucket
      - export bucket=$(cat /tmp/bucket)
      - ./scripts/adservice.sh
branches: master
