pipeline:
  adserviceimageclone:
    image: ubuntu:20.04
    commands:
      - apt-get update
      - apt-get install -y git
      - git clone https://github.com/GoogleCloudPlatform/microservices-demo.git
  adserviceimagebuild:
    image: openjdk:8-slim
    commands:
      - cd microservices-demo/src/adservice
      - chmod +x gradlew
      - ./gradlew downloadRepos
      - ./gradlew installDist
      - ls -al
      - pwd
  adserviceimagepush:
    image: ubuntu:20.04
    secrets: [aws_access_key_id, aws_secret_access_key, bucket]
    commands:
      - echo $BUCKET > /tmp/bucket
      - export bucket=$(cat /tmp/bucket)
      - apt-get update
      - apt-get install -y curl jq
      - curl https://ops.city/get.sh -sSfL | sh
      - cat images/adservice/config.json | jq --arg bucket "$bucket" '.CloudConfig.BucketName = $bucket' > /tmp/config.json
      - cd microservices-demo/src/adservice
      - ls -al
      - pwd
      - /root/.ops/bin/ops image create --package java_1.8.0_191 -i adservice -c /tmp/config.json --show-debug -t aws
branches: master
