pipeline:
  getamis:
    image: amazon/aws-cli
    secrets: [aws_access_key_id, aws_secret_access_key]
    environment:
      AWS_DEFAULT_REGION: eu-west-1
    commands:
      - ./scripts/amiexports.sh > amiexports
  deploy:
    image: cloudreach/sceptre:2.7.1
    secrets: [aws_access_key_id, aws_secret_access_key]
    commands:
      - eval $(cat amiexports)
      - sceptre status test
branches: master
